---
- name: eucalyptus initial tunnel zone configuration
  shell: |
    set -eu
    podman run --rm \
      --volume /usr/local/bin/eucalyptus-vpcmidotz-up.sh:/usr/local/bin/eucalyptus-vpcmidotz-up.sh:ro \
      --volume /etc/eucalyptus/eucalyptus.conf:/etc/eucalyptus/eucalyptus.conf:ro \
      --network host \
      docker.io/sjones4/midonet-cluster:5.2 \
      /usr/local/bin/eucalyptus-vpcmidotz-up.sh

- name: create eucalyptus account default vpc
  shell: |
    set -eu
    eval $(clcadmin-assume-system-credentials)
    eval $(euca-generate-environment-config --region localhost)
    if [ -z "$(euca-describe-subnets --filter default-for-az=true)" ]; then
      echo "Creating default vpc for eucalyptus account"
      euca-create-vpc $(euare-getcallerid | grep -oP "\\s*account\\s*=\\s*\\K.*\\s*")
    fi
  register: shell_result
  until: shell_result.rc == 0
  retries: 5
  changed_when: '"Creating default vpc for eucalyptus account" in shell_result.stdout'
