---
- name: install midonet nsdb dependency packages
  yum:
    name:
      - podman
    state: present
  tags:
    - image
    - packages

- name: cassandra systemd drop-in directory
  file:
    path: /etc/systemd/system/cassandra.service.d
    state: directory
    mode: 0755

- name: cassandra data directory
  file:
    path: /var/lib/cassandra
    state: directory
    mode: 0755

- name: cassandra environment sysconfig
  template:
    src: sysconfig-cassandra.j2
    dest: /etc/sysconfig/cassandra
    owner: root
    group: root
    mode: 0644

- name: cassandra systemd drop-in configuration
  copy:
    src: systemd-cassandra-overrides.conf
    dest: /etc/systemd/system/cassandra.service.d/overrides.conf
    owner: root
    group: root
    mode: 0644

- name: cassandra container and systemd service
  shell: |
    set -eu
    podman create --name cassandra \
      --env-file /etc/sysconfig/cassandra \
      --log-driver journald \
      --publish {{ eucalyptus_host_cluster_ipv4 }}:7000:7000 \
      --publish {{ eucalyptus_host_cluster_ipv4 }}:9042:9042 \
      --volume /var/lib/cassandra:/var/lib/cassandra \
      docker.io/library/cassandra:2.2.16
    podman generate systemd --name --timeout 60 --restart-policy always cassandra > /etc/systemd/system/cassandra.service
  args:
    creates: /etc/systemd/system/cassandra.service

- name: start cassandra service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: cassandra

- name: set zookeeper server id fact
  set_fact:
    eucalyptus_zookeeper_server_id: "{{ zookeeper_server_id | default(eucalyptus_host_cluster_ipv4) | regex_replace('^.*\\.(\\d+)$', '\\1') }}"

- name: zookeeper systemd drop-in directory
  file:
    path: /etc/systemd/system/zookeeper.service.d
    state: directory
    mode: 0755

- name: zookeeper data directory
  file:
    path: /var/lib/zookeeper/data
    state: directory
    mode: 0755

- name: zookeeper datalog directory
  file:
    path: /var/lib/zookeeper/datalog
    state: directory
    mode: 0755

- name: zookeeper environment sysconfig
  template:
    src: sysconfig-zookeeper.j2
    dest: /etc/sysconfig/zookeeper
    owner: root
    group: root
    mode: 0644

- name: zookeeper systemd drop-in configuration
  copy:
    src: systemd-zookeeper-overrides.conf
    dest: /etc/systemd/system/zookeeper.service.d/overrides.conf
    owner: root
    group: root
    mode: 0644

- name: zookeeper container and systemd service
  shell: |
    set -eu
    podman create --name zookeeper \
      --env-file /etc/sysconfig/zookeeper \
      --log-driver journald \
      --publish {{ eucalyptus_host_cluster_ipv4 }}:2181:2181 \
      --publish {{ eucalyptus_host_cluster_ipv4 }}:2888:2888 \
      --publish {{ eucalyptus_host_cluster_ipv4 }}:3888:3888 \
      --volume /var/lib/zookeeper/data:/data \
      --volume /var/lib/zookeeper/datalog:/datalog \
      docker.io/library/zookeeper:3.4.14
    podman generate systemd --name --timeout 60 --restart-policy always zookeeper > /etc/systemd/system/zookeeper.service
  args:
    creates: /etc/systemd/system/zookeeper.service

- name: start zookeeper service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: zookeeper

- name: wait for zookeeper service
  wait_for:
    sleep: 10
    host: "{{ eucalyptus_host_cluster_ipv4 }}"
    port: 2181
    timeout: 120

