---
- name: install bridge-utils package
  yum:
    name:
      - bridge-utils
    state: present
  tags:
    - image
    - packages

- name: create bridge interface
  template:
    src: ifcfg-brX.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ net_bridge_interface }}"
    force: no
    owner: root
    group: root
    mode: 0644

- name: bridge interface up
  command:
    cmd: "/usr/sbin/ifup {{ net_bridge_interface }}"
  register: command_result
  changed_when: "command_result is succeeded and command_result.stdout  != ''"

- name: install midonet dependency packages
  yum:
    name:
      - podman
    state: present
  tags:
    - image
    - packages

- name: midonet agent (midolman) systemd drop-in directory
  file:
    path: /etc/systemd/system/midonet-agent.service.d
    state: directory
    mode: 0755

- name: midonet agent (midolman) systemd drop-in configuration
  copy:
    src: systemd-midonet-agent-overrides.conf
    dest: /etc/systemd/system/midonet-agent.service.d/overrides.conf
    owner: root
    group: root
    mode: 0644

- name: midonet agent (midolman) logs directory
  file:
    path: /var/log/midonet-agent
    state: directory
    mode: 0755

- name: midonet agent (midolman) environment sysconfig
  template:
    src: sysconfig-midonet-agent.j2
    dest: /etc/sysconfig/midonet-agent
    owner: root
    group: root
    mode: 0644

- name: midonet agent (midolman) uuid sysconfig
  shell: |
    set -eu
    echo "UUID=$(uuidgen --random)" > /etc/sysconfig/midonet-agent-uuid
  args:
    creates: /etc/sysconfig/midonet-agent-uuid

- name: midonet agent (midolman) container and systemd service
  shell: |
    set -eu
    podman create --name midonet-agent \
      --env-file /etc/sysconfig/midonet-agent \
      --env-file /etc/sysconfig/midonet-agent-uuid \
      --net host \
      --privileged \
      --volume /var/log/midonet-agent:/var/log/midolman \
      docker.io/sjones4/midonet-agent:5.2
    podman generate systemd --name --timeout 60 --restart-policy always midonet-agent > /etc/systemd/system/midonet-agent.service
  args:
    creates: /etc/systemd/system/midonet-agent.service

- name: start midonet agent (midolman) service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: midonet-agent

